### PR TITLE
Add testfixtures wheel for galaxyproject/galaxy#2579.

### PR DESCRIPTION
**Pull request by jmchilton**
New PR, new build?

### CODE REVIEW

**Comment by jmchilton** [comment]
xref #100

**Comment by bgruening** [comment]
@jmchilton we need this one for the next stable release, aren't we?
The Jenkins output is not accessible, so I'm hesitate to merge it.
@galaxybot test this

**Comment by natefoo** [comment]
These built and were copied by Jenkins to https://depot.galaxyproject.org/starforge/wheels/build-96/

**Comment by jmchilton** [comment]
These have been copied to wheels.galaxyproject.org

**Comment by jmchilton** [comment]
Though I couldn't do it directly from orval for some reason (host problems?):

```
sites@orval:…alaxyproject.org/root/packages$ wget https://depot.galaxyproject.org/starforge/wheels/build-96/testfixtures-4.10.0.tar.gz
--2016-08-04 02:43:45--  https://depot.galaxyproject.org/starforge/wheels/build-96/testfixtures-4.10.0.tar.gz
Resolving depot.galaxyproject.org (depot.galaxyproject.org)... 54.172.110.33
Connecting to depot.galaxyproject.org (depot.galaxyproject.org)|54.172.110.33|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-08-04 02:43:45 ERROR 404: Not Found.
```

**Comment by natefoo** [comment]
orval is resolving depot as delirium. Because its resolver was pointing to a very old Galaxy DNS server IP that should have been decommissioned. Weird, and nice catch. This has been fixed.

**Pull request merged**
