### PR TITLE
Add netCDF4 wheel

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by bgruening** [comment]
Mh, I don't see that my dependencies (hdf5, netcdf) are installed here: https://jenkins.galaxyproject.org/job/starforge-wheels/109/console

@natefoo did I anything wrong here?

**Comment by martenson** [comment]
@galaxybot test this

**Comment by natefoo** [comment]
@galaxybot test this

**Comment by natefoo** [comment]
Oh sure, report it to the sysadmin and suddenly it works. ;P

**Comment by bgruening** [comment]
I don't get the joke :( It's still not working and I have no clue why. The jenkins logs are not really informative.

**Comment by natefoo** [comment]
@bgruening a common occurrence for sysadmins is that whenever someone comes to a sysadmin with a problem and tries to demo it, the problem does not occur whenever the sysadmin is watching. Also in this case another funny part (for me) is that @martenson is more the sysadmin of Jenkins than I am, so positions are reversed. =)

Fooling aside, I am looking in to the problem.

**Comment by natefoo** [comment]
@bgruening Ok, I think this should be fixed, please try rebasing or merging the latest commits on master (particularly 9d430664be7b94b45a1a25643574a6e564853b5c).

**Comment by natefoo** [comment]
Well this is progress. ;)

**Comment by bgruening** [comment]
It is, thanks! At least I see packages that are installed :)

**Comment by natefoo** [comment]
The error is misleading, it looks like the reason is that HDF5 as installed via yum is 1.6.10 and netCDF4 requires at least 1.8.0. CentOS 5... :sob: :sob: :sob:

**Comment by bgruening** [comment]
@natefoo thanks for looking at it. Is there a way I can use:https://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.14/bin/linux-centos5-x86_64-gcc482/

**Comment by natefoo** [comment]
It's also necessary to compile netcdf4 for this (especially because the version in CentOS 5 is very old). It looks like some portion of that static HDF5 library was compiled without `-fPIC`:

```
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/netCDF4/_netCDF4.o -L/home/nate/netcdf4/netcdf4/lib -L/home/nate/netcdf4/hdf5-1.8.14-linux-centos5-x86_64-gcc482-static/lib -Wl,-R/home/nate/netcdf4/netcdf4/lib -Wl,-R/home/nate/netcdf4/hdf5-1.8.14-linux-centos5-x86_64-gcc482-static/lib -lnetcdf -lhdf5_hl -lhdf5 -ldl -lm -lz -lcurl -lsz -o build/lib.linux-x86_64-2.7/netCDF4/_netCDF4.so
/usr/bin/ld: /home/nate/netcdf4/hdf5-1.8.14-linux-centos5-x86_64-gcc482-static/lib/libhdf5_hl.a(H5DS.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/home/nate/netcdf4/hdf5-1.8.14-linux-centos5-x86_64-gcc482-static/lib/libhdf5_hl.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

Static linking will fail. This is a problem for the OS X wheel, where we'll need the static versions since system versions of HDF5 and netCDF4 don't exist.

This may be a good case for trying the conda wheel build stuff you linked.

**Comment by nsoranzo** [comment]
netCDF4 provides all sort of binary wheels on PyPI, I think this can be closed.

**Pull request closed without merging**
