### PR TITLE
Automatic ppa updates for nginx

### PR DESCRIPTION
**Pull request by mvdbeek**
This hacky, ~~for trusty only atm~~, and it's tailored to my personal account, but maybe we could eventually do something like this for the galaxyproject ppa ? ping @jmchilton @natefoo @bgruening 

I've updated this to work on all ubuntu releases 14.04-16.10, so this is probably also going to work for future nginx updates.

### CODE REVIEW

**Comment by mvdbeek** [comment]
And [here](https://travis-ci.org/mvdbeek/starforge/builds/217800549) is a successful deployment for all recent ubuntu releases.

**Comment by bgruening** [comment]
Great work @mvdbeek! You rock!

**Comment by bgruening** [comment]
Thanks for working on this. In related news: https://www.nginx.com/blog/nginx-1-12-1-13-released/

nginx 1.12 was release with dynamic modules support afaik.

**Comment by mvdbeek** [comment]
I guess we're not going to see 16.04 (or 14.04) updated, but we should anyway figure out the procedure to make the upload module work (and how to distribute it) in the new nginx.

**Comment by bgruening** [comment]
@mvdbeek do we want to merge this as it is or do we wait for @natefoo to migrate this PR to the galaxyproject-ppa one?

**Comment by mvdbeek** [comment]
No, don't merge this yet. I do have the credentials now, just need a bit of
time to set it up.

**Comment by bgruening** [comment]
Cool!

**Comment by natefoo** [comment]
@mvdbeek how 'bout now?

**Comment by mvdbeek** [comment]
Yup, should be good to go.

**Comment by natefoo** [comment]
Thanks for getting this going!

**Pull request merged**
