### PR TITLE
Adds isa-rwval, a minimal isa-tools setup.

### PR DESCRIPTION
**Pull request by pcm32**
This is for the upcoming ISA Composite Datatype to be PRed to the main Galaxy project soon. This is a minimal ISA-Tools installation with stripped functionality to avoid heavy dependencies, but with everything needed for the composite datatype.

`isa.rwval-0.10.0-py2-none-any.whl` built without issues

Thanks!
Pablo

### CODE REVIEW

**Comment by pcm32** [comment]
@jmchilton @bgruening could I get a review here? It would help me unblock some other processes for us moving to 18.01 in the community images. Thanks!

**Comment by bgruening** [comment]
Looks good for me. @natefoo can you please do your magic :)

**Comment by martenson** [comment]
I think we should get this to pypi first and then build a wheel for it.

**Comment by djcomlab** [comment]
`isa-rwval` should now be in PyPI if you want to try it out.

**Comment by martenson** [comment]
@galaxybot test this

**Review by djcomlab — CHANGES_REQUESTED** [review]
The PyPI package is `isa-rwval` rather than `isa.rwval`.

**Comment by martenson** [comment]
There is a trouble with latest pip release when building wheels, not your fault, we will fix.

**Comment by natefoo** [comment]
Can you rebase this? It should work with the change to Starforge I just pushed.

**Comment by pcm32** [comment]
There, rebased and forced push.

**Comment by martenson** [comment]
@galaxybot test this

**Comment by martenson** [comment]
go bot, forge the wheels!

**Comment by nsoranzo** [comment]
It would be nice if you could build universal wheels, see https://github.com/ISA-tools/isa-rwval/pull/6 (not a showstopper for this PR).

**Comment by pcm32** [comment]
Any luck with pip? is it the 10.0 move? I have pinned pip on 9.0.3 on other projects as is 10.0 is giving us troubles. Thanks!

**Comment by martenson** [comment]
@pcm32 the wheels built alright I think

edit: I restarted the build so we can get universals

**Comment by martenson** [comment]
@galaxybot test this

**Comment by djcomlab** [comment]
@pcm32 The pin should be on 0.10.1 now (latest in PyPI).

**Comment by nsoranzo** [comment]
No need for starforge wheels, universal wheels for 0.10.1 are already available at PyPI: https://pypi.org/project/isa-rwval/0.10.1/#files

**Comment by martenson** [comment]
@nsoranzo they should go to cargo-port then, right?

**Comment by nsoranzo** [comment]
It would be good, but we haven't enforced that.

**Pull request closed without merging**
