### PR TITLE
Prepare for ripping pulsar out of Galaxy.

### PR DESCRIPTION
**Pull request by jmchilton**
pulsar-galaxy-lib is a new PyPI dependency that is Pulsar without galaxy-lib - it is meant to stand for pulsar as library for galaxy not a pulsar version of galaxy-lib.

### CODE REVIEW

**Comment by jmchilton** [comment]
Hmm... it is going to try to rebuild instead of just using the wheel from PyPI huh - and fail as a result.

I can hack the build I guess, would it be better to have an option to just reuse the PyPI wheel? I guess the circumvents the whole purpose of starforge? Hmm...

**Comment by natefoo** [comment]
It is going to try to rebuild, that is Starforge's entire purpose. Starforge makes sure we can reproducibly build wheels from their sdists, but yeah, it's almost pointless with pure python wheels.

Why is the sdist failing?

**Comment by jmchilton** [comment]
I don't know - it works from source :smile:.

**Comment by jmchilton** [comment]
Hey look - it worked! I did a starforge.

**Comment by natefoo** [comment]
https://depot.galaxyproject.org/starforge/wheels/build-58/

**Comment by jmchilton** [comment]
The wheels work for me and I'll open a PR to Galaxy soon.

**Pull request merged**
