### PR TITLE
Also build nginx for 18.04

### PR DESCRIPTION
**Pull request by mvdbeek**

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks @mvdbeek!
@natefoo can you have a look here please?

**Comment by CarlosHorro** [comment]
Hi :-) 
As we are interested on this, I don't know if I could help in any way to have this finished :-)

Greetings,
Carlos

**Comment by natefoo** [comment]
+1 from me. FWIW you should not need the nginx-upload-module anymore if you are using 18.05, due to the addition of chunked upload. We are still using it for Pulsar staging but if you're not doing that you can just run standard nginx and remove the upload module directives and Galaxy config options.

**Comment by bgruening** [comment]
@natefoo I can not find it on depot nor on the ppa? Did I missed it?

**Comment by mvdbeek** [comment]
Travis isn't activated for the starforge repo, I was uploading from my fork's master branch, which I have merged now. Now the upload fails with a connection error, will try again tomorrow.

**Pull request merged**
