### PR TITLE
Update nginx to keep up with ubuntu

### PR DESCRIPTION
**Pull request by mvdbeek**
@natefoo can you update the ppa after merging?
[Changelog](http://changelogs.ubuntu.com/changelogs/pool/main/n/nginx/nginx_1.4.6-1ubuntu3.4/changelog)

### CODE REVIEW

**Comment by bgruening** [comment]
@natefoo why is the old one not available anymore?
Docker now fails with:

```
E: Version '1.4.6-1ubuntu3.3ppa1' for 'nginx-extras' was not found
```

because I fixed it at this version to not get the other error when the ubuntu nginx package get favoured over the ppa package.

**Comment by mvdbeek** [comment]
that's --arguably-- good, given that these are security-fixes.

**Comment by bgruening** [comment]
Not really if your Docker build stops building unreliably.

**Comment by natefoo** [comment]
I did not remove the packages. It would appear that Launchpad or the PPA did this itself. =(

**Comment by natefoo** [comment]
https://help.launchpad.net/Packaging/PPA/Deleting

> The easiest alternative to replace a broken source is always to upload a package with a higher version number and let the system automatically supersede and remove the older version. You should not attempt to use deletion requests to re-upload the same source version with different contents, as this is still prevented even after the content has been deleted.

It appears to be by design and I am not sure of an easy fix. =(

**Comment by bgruening** [comment]
Ok, than it does not make sense to bind to a specific version and we need to live with the fact that some builds break as soon as Ubuntu increases the version number.

Thanks @natefoo!

**Comment by mvdbeek** [comment]
yup, thanks @natefoo

**Pull request merged**
