### PR TITLE
Build wheel for uwsgi.

### PR DESCRIPTION
**Pull request by jxtx**
(yes I accidentally made a branch)

### CODE REVIEW

**Comment by dannon** [comment]
Branches are fine in all projects except galaxyproject/galaxy, for whatever reason.

**Comment by dannon** [comment]
@natefoo It looks in the traceback like we're using python2.6.  I don't know if that's the cause for the build failure here, but should we bump that to 2.7?

**Comment by natefoo** [comment]
I don't think it's the cause but it wasn't supposed to be using those images - I needed to update Starforge on the build server and now it should use different images (to build manylinux1 wheels).

**Comment by natefoo** [comment]
@galaxybot test this

**Comment by jxtx** [comment]
@galaxybot test this

**Comment by natefoo** [comment]
Weirdly it didn't detect the changes to `wheels.yml` so none were actually built. I'll give a try building them.

**Comment by martenson** [comment]
@natefoo I think it tried to build it the first time (https://jenkins.galaxyproject.org/job/starforge-wheels/68/console) however it failed and in the second commit there is "no wheel change" compared to the first one so it did not trigger the build?

**Pull request merged**
