### PR TITLE
add build instructions for openms

### PR DESCRIPTION
**Pull request by bgruening**
This is not perfect but hopefully get the job done. 

Things to improve:
- LDFLAG magic is not working and we need to export LD_LIBRARY_PATH

### CODE REVIEW

**Comment by bgruening** [comment]
@natefoo I exported a few shared object files and enabled debian backports. Now this builds with `./build galaxy openms`.

Could you please upload this tarball and the [tpp tarball](https://github.com/galaxyproject/docker-build/pull/13) into the depot?

If you have any ideas how to make the copying if `*.so` files smarter, please let me know.

**Comment by natefoo** [comment]
I wouldn't say it is a vast improvement but you could do something like what's done in [ucsc](https://github.com/galaxyproject/docker-build/blob/ca5a989603dc9cbc69320af6a5b338d30fe3d62f/ucsc/build.sh).

The problem is you already have to know which linked libs are non-standard. I suppose if we had some kind of lib-collecting utility function that already knew which libs to exclude, that'd help?

**Comment by natefoo** [comment]
@bgruening I've uploaded both to depot.galaxyproject.org

**Comment by bgruening** [comment]
Thanks @natefoo! 

For reference:
- https://depot.galaxyproject.org/package/linux/x86_64/openms/openms-2.0-Linux-x86_64.tar.gz
- https://depot.galaxyproject.org/package/linux/x86_64/tpp/tpp-4.8.0-Linux-x86_64.tar.gz

**Pull request merged**
