### PR TITLE
Add bag format wheels.

### PR DESCRIPTION
**Pull request by jmchilton**

### CODE REVIEW

**Comment by jmchilton** [comment]
Looks related to build issues: https://github.com/pypa/pypi-legacy/issues/322

**Comment by jmchilton** [comment]
@natefoo Any chance you can find some time to get this wheel to work? I'm trying increasingly bizarre pip invocations and nothing is working. The 18.05 should probably not be released until this wheel is available it is also blocking progress on the 18.05 Docker image I think.

**Comment by natefoo** [comment]
I think it's an issue of PyPI no longer supporting older TLS versions because the manylinux image is CentOS 5-based. There's a newer OpenSSL installed, though, but I guess perhaps it's not being used in this case? Dunno, I can take a look. Were the pip/setuptools upgrades just to attempt to fix that problem, or are they needed for bagit?

**Comment by jmchilton** [comment]
Just attempts to fix the problem, though it does need setuptools_scm - not sure if this would come automatically or not though.

**Comment by natefoo** [comment]
@galaxybot test this

**Comment by natefoo** [comment]
@jmchilton eh?

**Comment by natefoo** [comment]
@galaxybot test this

**Pull request merged**
