### PR TITLE
pyjwkest wheel

### PR DESCRIPTION
**Pull request by VJalili**
This is a required package for python social core (#185 ).

### CODE REVIEW

**Comment by dannon** [comment]
@VJalili Doesn't look like it actually built the new wheels, here.  Only the pyjwkest one exists in the build directories.

**Comment by VJalili** [comment]
Does that mean we can't have wheels built for other dependencies ?

**Comment by dannon** [comment]
We can, the build process just broke (didn't see the new package additions as changes it needed to build, I think).  I can see why tomorrow.

**Comment by VJalili** [comment]
I can break this in two PRs if that helps.

**Pull request closed without merging**
