### PR TITLE
Add azure wheel.  Conditional requirement for azure object store.

### PR DESCRIPTION
**Pull request by dannon**

### CODE REVIEW

**Comment by alexlenail** [comment]
@dannon that was easy =)

**Comment by dannon** [comment]
Looks like azure-common and azure-nspkg are dependencies of azure-storage, I'll update this.  Not sure why the build is failing though.

**Comment by natefoo** [comment]
@galaxybot test this

The build failure was due to a bug in Starforge that had already been fixed, but the docker image for purepy wheels needed to be rebuilt to include the fix.

**Comment by natefoo** [comment]
Hey @martenson this trigger didn't fire. Is it because I keep putting other text in the trigger comment? That used to be possible (it's fine if it's not possible anymore, just want to know if this is why it fails).

**Comment by natefoo** [comment]
@galaxybot test this

**Comment by natefoo** [comment]
To answer myself: yes.

**Comment by martenson** [comment]
@natefoo we can probably regexpizize the trigger but now it is comment on its own as I had problems with Jenkins malforming the regexps during upgrades

**Comment by natefoo** [comment]
@martenson no problem, not a big deal, thanks!

**Comment by natefoo** [comment]
@zfrenchee if you rebase or merge the latest changes from the master branch, these should build properly.

**Comment by alexlenail** [comment]
@natefoo I don't have privileges on this repo -- would you like me to do this via fork / new pr?

**Comment by dannon** [comment]
Done.

**Comment by natefoo** [comment]
Whoops, didn't realize it was @dannon's PR.

Here's the wheels: https://depot.galaxyproject.org/starforge/wheels/build-129/

**Comment by bgruening** [comment]
So I guess we can merge this? Thanks everyone!

**Comment by natefoo** [comment]
These wheels have been copied to wheels.galaxyproject.org

**Pull request merged**
