### PR TITLE
Add testfixtures wheel for galaxyproject/galaxy#2579.

### PR DESCRIPTION
**Pull request by jmchilton**

### CODE REVIEW

**Comment by jmchilton** [comment]
@galaxybot test this

**Comment by jmchilton** [comment]
@natefoo Rebasing did not fix this problem for me :frowning:.

**Comment by natefoo** [comment]
@galaxybot test this

Ran `git fetch master` by hand, apparently the workspaces are being recycled for the starforge-wheels builder and Jenkins only fetches `+refs/pull/*:refs/remotes/origin/pr/*` on build.

**Comment by natefoo** [comment]
Triggering these builds via @galaxybot still doesn't work. :weary:

**Pull request closed without merging**
