### PR TITLE
Relocate libbz2 into the exported tarball.

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by natefoo** [comment]
+1

The IUC has commit access on this repo and are welcome to be involved in and merge PRs. =)

**Comment by hexylena** [comment]
(Sorry @natefoo, I didn't notice this PR or I would've reviewed it)

**Comment by natefoo** [comment]
No worries, I just wanted to make it official policy that I have released this repo forth unto the community and my approval is not required to merge PRs. =)

**Comment by bgruening** [comment]
Thanks @natefoo and @erasche this was quick! Back to proteomics hacking.

**Pull request merged**
