### PR TITLE
Add wheels for jstree and dictobj.

### PR DESCRIPTION
**Pull request by jmchilton**
These are things in the code base that could be removed I think?

Do I need to do anything else or just add these to this file?

### CODE REVIEW

**Comment by natefoo** [comment]
https://depot.galaxyproject.org/starforge/wheels/build-26/

**Comment by martenson** [comment]
@natefoo was that comment automated?

**Comment by natefoo** [comment]
No, I was just too lazy to type anything else.

**Comment by jmchilton** [comment]
@natefoo That is fine, as long as you know I have no clue what to do with that link and intend to ignore it :laughing:.

**Comment by natefoo** [comment]
@jmchilton in theory someone should test the wheels...

**Comment by jmchilton** [comment]
So after I test them what happens? Is this documented somewhere?

**Comment by martenson** [comment]
I assume you put them in https://wheels.galaxyproject.org/packages/, modify requirements and remove from the codebase?

**Comment by natefoo** [comment]
You put them on https://wheels.galaxyproject.org/, modify requirements, and remove from the codebase. ;D

No documentation, still ironing out the process. I'd like to have Jenkins actually do the copying of wheels from depot to wheels after a comment on the PR.

**Comment by martenson** [comment]
I copied the wheels to https://wheels.galaxyproject.org/packages/

```
jstree-0.4.tar.gz
jstree-0.4-py2-none-any.whl
dictobj-0.3.1-py2-none-any.whl
dictobj-0.3.1.tar.gz
```

**Pull request merged**
