### PR TITLE
Python Social Auth Core package.

### PR DESCRIPTION
**Pull request by VJalili**
I am not sure how dependancies of each wheel are managed, but this library has the following dependencies: 

    python-openid>=2.2.5
    pyjwkest>=1.0.1
    requests>=2.9.1
    oauthlib>=1.0.3
    requests-oauthlib>=0.6.1
    six>=1.10.0
    PyJWT>=1.4.0
    cryptography>=2.1.1

### CODE REVIEW

**Comment by martenson** [comment]
this error is in the console:

```
  File "/opt/_internal/cpython-3.6.0/lib/python3.6/site-packages/auditwheel/wheeltools.py", line 191, in add_platforms
    raise WheelToolsError('Cannot add platforms to pure wheel')
auditwheel.wheeltools.WheelToolsError: Cannot add platforms to pure wheel
social_auth_core-1.5.0-cp27-cp27m-manylinux1_x86_64.whl missing, build failed?
social_auth_core-1.5.0-cp27-cp27mu-manylinux1_x86_64.whl missing, build failed?
Exiting due to missing wheels
```

**Comment by martenson** [comment]
it seems we have a bug there somewhere since we are triggering https://github.com/pypa/auditwheel/blob/master/auditwheel/wheeltools.py#L190

**Comment by VJalili** [comment]
Thanks for checking this @martenson ; any suggestion ?

**Comment by martenson** [comment]
@VJalili Sadly no, I do not know much about this infrastructure, but I believe @natefoo will be able to fix it once he gets back - that might be after holidays though.

**Comment by dannon** [comment]
The error is that this is not a platform wheel, it's purepy.  I pushed a fix.

**Comment by VJalili** [comment]
Thanks @martenson and @dannon

**Comment by dannon** [comment]
Available at https://wheels.galaxyproject.org/simple/social_auth_core/

**Comment by VJalili** [comment]
@dannon Thanks for wheel. 

I'm not sure if wheels are supposed to encapsulate all the dependencies of a project. If they are, then I guess, at least, [OpenID Connect dependencies](https://github.com/python-social-auth/social-core/blob/master/requirements-openidconnect.txt) of PSA are not packed.

**Comment by dannon** [comment]
@VJalili Correct, this is just a wheel for that one library, without external dependencies.

**Comment by VJalili** [comment]
Thanks.

**Pull request merged**
