### PR TITLE
Update cloudauthz version to 0.1.0

### PR DESCRIPTION
**Pull request by VJalili**

### CODE REVIEW

**Comment by dannon** [comment]
Mjolnir is offline temporarily, when we get it up this should build.

**Comment by VJalili** [comment]
Is Mjolnir back online?

**Comment by dannon** [comment]
@VJalili We're working on building it a different way, using new infrastructure, as mentioned in direct messages.  I'll close this out.

xref #https://github.com/galaxyproject/starforge-recipes/pull/10

**Comment by nsoranzo** [comment]
Starforge recipes are being moved to https://github.com/galaxyproject/starforge-recipes/ , cloudauthz was just upgraded to 0.1.0 in https://github.com/galaxyproject/starforge-recipes/pull/10 . The wheels are already live on https://wheels.galaxyproject.org/simple/cloudauthz/ .

**Comment by VJalili** [comment]
@dannon Sorry, I think I missed the direct message. But this sounds good. Thank you both.

**Pull request closed without merging**
