### PR TITLE
Update CloudBridge to its current latest version

### PR DESCRIPTION
**Pull request by VJalili**
Another update to the `CloudBridge`. 
The newest version is available at the following link: 
https://pypi.org/project/cloudbridge/

### CODE REVIEW

**Comment by bgruening** [comment]
Ping us harder if we miss these PRs, sorry. Hope it is building now.

**Comment by VJalili** [comment]
Thanks. I guess it should build now; fingers crossed :)

**Comment by VJalili** [comment]
Is the wheel (i.e., cloudbridge v0.3.3) supposed to be available at [this](https://wheels.galaxyproject.org/packages/) page?

**Comment by dannon** [comment]
Wheels deployed.  We probably shouldn't merge these *until* that has been done for now (long term plan is to automate, iirc), just to keep track of this sort of thing.

**Comment by VJalili** [comment]
@dannon Thanks.

**Comment by bgruening** [comment]
@dannon if this does not happen automatically, who can deploy these wheels, who to ping :)

**Comment by dannon** [comment]
Feel free to ping me, don't want to speak for anyone else, though several others can deploy them.

**Pull request merged**
