### PR TITLE
add social auth wheel with ELIXIR AAI support

### PR DESCRIPTION
**Pull request by bgruening**
We need this release as it contains important fixed for ELIXIR AAI support.

ping @nsoranzo

### CODE REVIEW

**Comment by nsoranzo** [comment]
New wheels should be added to https://github.com/galaxyproject/starforge-recipes/

**Comment by bgruening** [comment]
Documentation should be updated ...

**Comment by nsoranzo** [comment]
Is there any documentation :D ?

**Comment by nsoranzo** [comment]
More seriously, look at the start of the file.

**Comment by bgruening** [comment]
Yes, see here: https://github.com/galaxyproject/starforge#python-wheels

**Pull request closed without merging**
