### PR TITLE
Add wheel for ipaddress.

### PR DESCRIPTION
**Pull request by jmchilton**
Module will let Galaxy reason about ipaddresses - a good non-hacky way to verifying the upload tool for instance isn't trying to fetch content from an intranet ip address unless said IP appears in some sort of include list.

Ping @erasche.

### CODE REVIEW

**Comment by hexylena** [comment]
Brilliant, thank you! (Did you happen to see my [branch](https://github.com/erasche/galaxy/tree/local-network), or just planning ahead for your own work? Will have time to finish this this weekend.)

**Comment by jmchilton** [comment]
@erasche No branch yet - just wanted this available.

**Comment by hexylena** [comment]
@jmchilton I'll do this tonight, if it exceeds that, please feel free to take over. (I'm trying to be better about making hard commitments of "If I don't do X by Y time, I won't 'hold' onto a bug")

**Comment by jmchilton** [comment]
@natefoo - this was merged before the wheels were transferred and then Jenkins lost the build. Can you resolve that?

**Comment by natefoo** [comment]
I suspect galaxybot does not look at terminal PRs, but just in case...

**Comment by natefoo** [comment]
@galaxybot test this

**Comment by natefoo** [comment]
Upon closer inspection, where would the test results even show up, since there's no test results area on closed PRs. =P

**Comment by natefoo** [comment]
Built with `starforge wheel ipaddress` and copied to wheels.galaxyproject.org

**Comment by jmchilton** [comment]
Thanks @natefoo 😅

**Pull request merged**
