### PR TITLE
Build platform-specific wheels for watchdog

### LINKED ISSUE #5009: Galaxy startup fails during migration due to too many open files
Encountered this during a planemo test but it seems to be a Galaxy issue. Migrations don't seem to close file handles? See attached output log of ```planemo t --install_galaxy```

[errors.txt](https://github.com/galaxyproject/galaxy/files/1472478/errors.txt)

`OSError: [Errno 24] Too many open files: '/private/var/folders/55/98d70mnj5ps9nwffx39skrw40009rn/T/tmp2lhrw74a/galaxy-dev/lib/galaxy/datatypes/converters/interval_to_interval_index_converter.py'`

`IOError: [Errno 24] Too many open files: './lib/galaxy/datatypes/converters/bed_to_gff_converter.xml'`

### PR DESCRIPTION
**Pull request by mvdbeek**
Should fix https://github.com/galaxyproject/galaxy/issues/5009.

### CODE REVIEW

**Comment by natefoo** [comment]
1. It looks like `starforge wheel_diff` doesn't show a diff for wheels moved between the purepy/platform sections.
2. I did manage to [trigger it manually in Jenkins](https://jenkins.galaxyproject.org/job/starforge-wheels/278/) but as I feared, it failed because the Linux wheels are pure python

I created an issue for a fix in #184. In the meantime, restrict this to the `macos-wheel` imageset and that should hopefully build the macOS wheel, which is all we need at the moment since we already have the purepy wheel (and they're trivial to create anyway).

**Comment by mvdbeek** [comment]
Alright, I think that worked, thanks @natefoo !

**Comment by natefoo** [comment]
Ok, copied to wheels.galaxyproject.org. Thanks!

**Comment by mvdbeek** [comment]
Thanks @natefoo, this fixes the issue for me!

**Pull request merged**
