### PR TITLE
Added UCSC kent tools build script

### PR DESCRIPTION
**Pull request by hexylena**
@bgruening seemed interested in this as well.

### CODE REVIEW

**Comment by bgruening** [comment]
@erasche this works for me: https://gist.github.com/bgruening/e2474cd5bf508c04685d

**Comment by hexylena** [comment]
Hmm, forgot libs, excellent catch @bgruening that would've caused errors. Now I know why you asked if I have `libmysqlclient-dev` installed. Ugh developers who don't use autoconf, custom makefiles drive me crazy.

**Comment by bgruening** [comment]
@erasche I'm just confused that this PR is working for you and that you do not need to have `libmysqlclient.so`. Building with `make utils` works for me but I need `openssl.h`. So if you do not need `libssh-dev` maybe it's better to use this PR. Still I don't know why your tools working without libmysql.
Feel free to proceed as you like.

I'm fine with everything that convinces @natefoo to merge this and put this into the depot!

**Comment by hexylena** [comment]
`ldd $toolname` shows that they're linked into `/usr/lib/**`. I guess it just happens that the docker container that I build in happens to have the same libs in the same place that the host does? I don't need libssh, and I don't see a single thing linked to ssh, strange that you need it.

**Comment by hexylena** [comment]
Well, even if it does need libssl, whatever, not a big deal.

**Comment by hexylena** [comment]
@bgruening Committed changes based on your suggestions (on your behalf since it was your gist+ideas after all :) )

**Comment by bgruening** [comment]
Fancy, didn't know that this is possible with git and gist! Thanks.

**Comment by hexylena** [comment]
I just used `--author "Name <email>"`, that's all.

**Comment by bgruening** [comment]
This failed on my site with: `ldd: ./faToTwoBit: not regular file`

**Comment by hexylena** [comment]
..............................................
I'm about ready to give up on UCSC tools.

**Comment by natefoo** [comment]
@erasche the only problem with your build.sh was a missing `\;` at the end of the second find, and that `ldd` was running in the current working dir rather than on `/build/dest/bin/faToTwoBit`.

Here's a version that works for me:

https://gist.github.com/natefoo/f767fd27cb675af45daa

This includes setting a runtime linker path with `$ORIGIN` so that `$LD_LIBRARY_PATH` should be unecessary. You can ignore the `${build}` stuff if you like, I like to set `build=/host/build.$(hostname)` to easily see the intermediate steps during development. Including all of the libs in the `libc6` package causes a segfault on modern systems so I pared this down to just the others (minus libz).

**Comment by hexylena** [comment]
@natefoo great, thanks for fixing this. I'll patch in your changes and ping you when that's done. I appreciate the comments, those are all good to know.

**Comment by hexylena** [comment]
@natefoo updated. Thanks for the fixes! Can't believe I forgot my `\;`

**Pull request merged**
