### PR TITLE
Bump to the new 8.4 pysam (galaxy flavor)

### PR DESCRIPTION
**Pull request by dannon**
Ping @natefoo Sanity check?

### CODE REVIEW

**Comment by natefoo** [comment]
Looks correct to me. Now we wait...

**Comment by natefoo** [comment]
https://depot.galaxyproject.org/starforge/wheels/build-42/

**Comment by natefoo** [comment]
@dannon I copied the wheels to wheels.galaxyproject.org. Want to PR the version change on 16.01?

**Comment by dannon** [comment]
Thanks!  And, will do.

**Pull request merged**
