### PR TITLE
Pysam galaxy version bump to include a fix from @nsoranzo

### PR DESCRIPTION
**Pull request by dannon**
See https://github.com/dannon/pysam/pull/2

### CODE REVIEW

**Comment by nsoranzo** [comment]
Something went wrong at the end of the build. @natefoo any idea?

**Comment by dannon** [comment]
(this one might succeed)

**Comment by nsoranzo** [comment]
@galaxybot test this

**Comment by natefoo** [comment]
I bumped the timeout to 30 minutes.

**Comment by natefoo** [comment]
@galaxybot test this

**Comment by dannon** [comment]
@natefoo Thanks!

**Comment by nsoranzo** [comment]
`Build timed out (after 30 minutes). Marking the build as aborted.` :cry:

**Comment by dannon** [comment]
@galaxybot test this

**Comment by dannon** [comment]
I bumped it up to an hour and it finally worked.

**Comment by dannon** [comment]
Wheels copied.

**Pull request merged**
