### PR TITLE
Add uWSGI wheel

### PR DESCRIPTION
**Pull request by natefoo**
This supercedes #95 and #114.

### CODE REVIEW

**Comment by natefoo** [comment]
Jenkins? Hello Jenkins?

@martenson?

**Comment by martenson** [comment]
@galaxybot test this

**Comment by martenson** [comment]
@galaxybot test this

**Comment by martenson** [comment]
boom, shakalaka!

**Comment by martenson** [comment]
@natefoo a secret was missing from ghprb webhook; when I switched to using it I forgot about Starforge, sorry

**Comment by natefoo** [comment]
@martenson thanks!

Now, why is it claiming failure? =l

**Comment by martenson** [comment]
maybe this sent error exit code?

```
Possible sdists missing, build failed?
Build step 'Execute shell' marked build as failure
```

**Comment by natefoo** [comment]
@martenson indeed.

https://depot.galaxyproject.org/starforge/wheels/build-161/

**Comment by natefoo** [comment]
uWSGI 2.0.15 has been released, meaning that we no longer need to use a development build of uWSGI 2.0. I updated the PR and the new wheels are now on wheels.galaxyproject.org.

**Comment by bgruening** [comment]
Then let's get this in.

**Pull request merged**
