### PR TITLE
Bump version of paramiko and Fabric for paramiko-based shell job runn…

### PR DESCRIPTION
**Pull request by mvdbeek**
…er improvements.

### CODE REVIEW

**Comment by mvdbeek** [comment]
Hey @natefoo, can you do your magic please?

**Comment by jmchilton** [comment]
I'll see if I can get this transferred...

**Comment by jmchilton** [comment]
It looks like Jenkins deleted these wheels and I can't figure out how to trigger a new build - can you close this PR and open a new one?

**Comment by mvdbeek** [comment]
I think opening/closing is trggering a new run, no ?

**Comment by mvdbeek** [comment]
Should be in `/var/jenkins/workspace/starforge-wheels/wheels/dist/build-199` according to the logs

**Comment by jmchilton** [comment]
Thanks @mvdbeek! All I had to do was fetch my old laptop out of storage and spend an hour guessing paths and keys - I got this! These dependencies are reproducible in the sense that I need to reproduce my old laptop and keystrokes to republish them.

**Comment by natefoo** [comment]
For they record, they were copied here: https://depot.galaxyproject.org/starforge/wheels/build-199/

I have some work for p4 somewhere that'd allow us to automatically copy wheels to wheels.galaxyproject.org with a PR comment. Not completely done but it wouldn't take much to finish it off.

**Pull request merged**
