### PR TITLE
add h5py

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by bgruening** [comment]
xref: https://github.com/galaxyproject/starforge/pull/44
@natefoo can we get this or something similar into Galaxy?

**Comment by natefoo** [comment]
Much like [we do for psycopg2](https://github.com/galaxyproject/starforge/blob/0a5ccba23816a65f731412f5e163ffd46cd7fa93/wheels/build/wheels.yml#L37), it's likely that a modern HDF5 will need to be installed. The version installable under manylinux1's CentOS 5 image will be very old. It looks like they [might've previously produced portable builds?](https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.13/bin/), so that might avoid having to compile it.

**Comment by natefoo** [comment]
The work has already been done for us: [PyPI](https://pypi.python.org/pypi/h5py/2.7.1), [h5py-wheels](https://github.com/MacPython/h5py-wheels).

I can copy the wheels on to wheels.galaxyproject.org to ensure they don't disappear on us, but they should work today with `h5py==2.7.1` in Galaxy's `requirements.txt`.

**Comment by natefoo** [comment]
See galaxyproject/cargo-port#131 for wheel archiving, I'm closing this one.

**Pull request closed without merging**
