### PR TITLE
pysam 0.13

### PR DESCRIPTION
**Pull request by dannon**
This could be the one!

### CODE REVIEW

**Comment by dannon** [comment]
`Exception: Connection to guest SSH server failed` -- looks like the osx wheel build infrastructure is having problems?  (maybe ping @natefoo @martenson ?)

**Comment by natefoo** [comment]
@galaxybot test this

**Comment by dannon** [comment]
(Just curious; I retriggered the job manually several times -- does `@galaxybot test this` do extra magic?)

**Comment by natefoo** [comment]
It shouldn't do anything different, no. Did you trigger it directly from within Jenkins, or just delete the galaxybot comments?

I triggered it now so I could watch the qemu/kvm launch process.

**Comment by dannon** [comment]
I usually retrigger runs directly from jenkins, just wanted to make sure I wasn't missing out on extra galaxybot magic!

**Comment by natefoo** [comment]
Well, this is odd, `jenkins` on `mjolnir0` is not a member of the `kvm` group. I have no idea how it was ever able to run qemu/kvm before.

**Comment by natefoo** [comment]
Fixed in galaxyproject/infrastructure-playbook@93480aed148c9dd839adeaaf7b7fd9c9d8aa820d

**Comment by natefoo** [comment]
@galaxybot test this

**Comment by dannon** [comment]
Hooray, thanks!

**Comment by natefoo** [comment]
@galaxybot test this

**Comment by natefoo** [comment]
Had to restart the jenkins agent to pick up the group change.

**Comment by mvdbeek** [comment]
So this is ready to go ?

**Comment by dannon** [comment]
Looks like it should be; I'll doublecheck and deploy the wheels in a few, and will then merge.

**Comment by dannon** [comment]
Wheels published.

**Pull request merged**
